/**
 * =============================================================================
 * ErrorCodeEnum - أكواد أخطاء التطبيق
 * =============================================================================
 */

export enum ErrorCode {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  BAD_REQUEST = 'BAD_REQUEST',

  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID = 'AUTH_MFA_INVALID',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_PASSWORD_WEAK = 'AUTH_PASSWORD_WEAK',

  // Wallet
  WALLET_INSUFFICIENT_BALANCE = 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_TRANSACTION_FAILED = 'WALLET_TRANSACTION_FAILED',
  WALLET_CURRENCY_MISMATCH = 'WALLET_CURRENCY_MISMATCH',
  WALLET_LIMIT_EXCEEDED = 'WALLET_LIMIT_EXCEEDED',
  WALLET_FROZEN = 'WALLET_FROZEN',

  // Booking
  BOOKING_SLOT_UNAVAILABLE = 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_ALREADY_EXISTS = 'BOOKING_ALREADY_EXISTS',
  BOOKING_CANCEL_TOO_LATE = 'BOOKING_CANCEL_TOO_LATE',
  BOOKING_NOT_FOUND = 'BOOKING_NOT_FOUND',

  // Order
  ORDER_INVALID_ITEMS = 'ORDER_INVALID_ITEMS',
  ORDER_PAYMENT_FAILED = 'ORDER_PAYMENT_FAILED',
  ORDER_ALREADY_SHIPPED = 'ORDER_ALREADY_SHIPPED',
  ORDER_CANNOT_CANCEL = 'ORDER_CANNOT_CANCEL',

  // Fraud
  FRAUD_BLOCKED = 'FRAUD_BLOCKED',
  FRAUD_CHALLENGE = 'FRAUD_CHALLENGE',
  DEVICE_NOT_TRUSTED = 'DEVICE_NOT_TRUSTED',

  // KYC
  KYC_ALREADY_VERIFIED = 'KYC_ALREADY_VERIFIED',
  KYC_DOCUMENT_INVALID = 'KYC_DOCUMENT_INVALID',
  KYC_LIMIT_REACHED = 'KYC_LIMIT_REACHED',

  // FX
  FX_RATE_NOT_AVAILABLE = 'FX_RATE_NOT_AVAILABLE',
  FX_INVALID_PAIR = 'FX_INVALID_PAIR',
  FX_LIMIT_EXCEEDED = 'FX_LIMIT_EXCEEDED',
}
